### ISSUE TITLE
Unable to retrieve map

### ISSUE THREAD

**Issue by antoweb** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#271] opened 2022-04-08 16:06 UTC
After installing and configuring custom component after reboot receive this error in log

2022-04-08 18:04:54 DEBUG (SyncWorker_8) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map, reasons: Logged in - True, map name - retry, device retrieved - True

**Comment by antoweb** [comment] 2022-04-08 16:07
My vaccum is xiaomi mop 2 model

**Comment by antoweb** [comment] 2022-04-08 16:44
After a restart the map seems to be extracted but:

'map.cur_cleaning_path.error': '-704220043 Property value error', 'map.build_map': 0, 'map.has_new_map': 0, 'map.map_uploads.error': '-704030013 Property is not readable', 'sweep.repeat_state': 0, 'sweep.door_state': 1, 'sweep.cloth_state': 1, 'sweep.suction_state': 3, 'sweep.water_state': 1, 'sweep.mop_route': 0, 'sweep.side_brush_life': 97, 'sweep.side_brush_hours': 176, 'sweep.main_brush_life': 98, 'sweep.main_brush_hours': 356, 'sweep.hypa_life': 97, 'sweep.hypa_hours': 176, 'sweep.mop_life': 97, 'sweep.mop_hours': 176, 'sweep.direction.error': '-704030013 Property is not readable', 'sweep.time_zone': -7200, 'sweep.cur_lang': 'it_IT', 'sweep.cleaning_time': 14, 'sweep.cleaning_area': 12, 'sweep.multi_prop_vacuum': '[0,1,1,3,1,0,-7200,14,12.5,0,"it_IT","33470260210948870","it_IT",3,-1,0,0,1,2]', 'sweep.tank_shake': 1, 'sweep.shake_shift': 2, 'alarm': 1, 'alarm.volume': 10, 'battery.battery_level': 64, 'state_updater': 'cloud', 'sub_entities': ['battery-3.battery_level-1']}

**Comment by antoweb** [comment] 2022-04-08 16:45
Error:

2022-04-08 18:45:17 DEBUG (SyncWorker_9) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map, reasons: Logged in - True, map name - retry, device retrieved - True

**Comment by PiotrMachowski** [comment] 2022-04-08 17:05
> After a restart
> 
> **'map.cur_cleaning_path.error': '-704220043 Property value error', 'map.build_map': 0, 'map.has_new_map': 0, 'map.map_uploads.error': '-704030013 Property is not readable'**, 'sweep.repeat_state': 0, 'sweep.door_state': 1, 'sweep.cloth_state': 1, 'sweep.suction_state': 3, 'sweep.water_state': 1, 'sweep.mop_route': 0, 'sweep.side_brush_life': 97, 'sweep.side_brush_hours': 176, 'sweep.main_brush_life': 98, 'sweep.main_brush_hours': 356, 'sweep.hypa_life': 97, 'sweep.hypa_hours': 176, 'sweep.mop_life': 97, 'sweep.mop_hours': 176, **'sweep.direction.error': '-704030013 Property is not readable'**, 'sweep.time_zone': -7200, 'sweep.cur_lang': 'it_IT', 'sweep.cleaning_time': 14, 'sweep.cleaning_area': 12, 'sweep.multi_prop_vacuum': '[0,1,1,3,1,0,-7200,14,12.5,0,"it_IT","33470260210948870","it_IT",3,-1,0,0,1,2]', 'sweep.tank_shake': 1, 'sweep.shake_shift': 2, 'alarm': 1, 'alarm.volume': 10, 'battery.battery_level': 64, 'state_updater': 'cloud', 'sub_entities': ['battery-3.battery_level-1']}

This entry seems to be trimmed

**Comment by antoweb** [comment] 2022-04-08 22:48
sorry error was of another addon

**Comment by PiotrMachowski** [comment] 2022-04-09 00:44
Please provide your config and exact model code.

**Comment by antoweb** [comment] 2022-04-09 06:35
Config:
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
  
Model: ijai.vacuum.v3 - MJST1SHW

**Comment by PiotrMachowski** [comment] 2022-04-09 11:54
This model is not supported at this moment.

Duplicate of #251

**Closed by PiotrMachowski** 2022-04-09 11:54 UTC
