### ISSUE TITLE
Platform error camera.xiaomi_cloud_map_extractor - No module named 'Crypto'

### ISSUE THREAD

**Issue by HelloMorningStar** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#103] opened 2021-04-14 14:51 UTC
Platform error camera.xiaomi_cloud_map_extractor - No module named 'Crypto'

**Comment by PiotrMachowski** [comment] 2021-04-16 12:05
Duplicate of #101

**Closed** 2021-04-16 12:05 UTC
Labels: bug
