### ISSUE TITLE
Warning 2021.12

### ISSUE THREAD

**Issue by sagitt** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#209] opened 2021-12-26 21:02 UTC
this warning in logs:

2021-12-26 22:00:57 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.mappa_robot_aspirapolvere (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by PiotrMachowski** [comment] 2021-12-26 21:52
Duplicate of #196

**Closed by PiotrMachowski** 2021-12-26 21:52 UTC
