### ISSUE TITLE
 Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds 

### ISSUE THREAD

**Issue by jkms** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#104] opened 2021-04-16 18:14 UTC
In the logs I see:
```
 Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds 
 Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
```

This is my `configuration.yaml`
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: <ip>
    token: <token>
    username: <username>
    password: <password>
    country: "us"
    draw: ['all']
    attributes:
      - calibration_points
```

I don't have pi-hole or any adblocking on my router, but I still don't see an image...  Stuck.  What do I check next?

**Comment by saar-win** [comment] 2021-04-29 15:15
mine taking over 2 hours :|

**Comment by PiotrMachowski** [comment] 2021-04-29 15:57
duplicate of #82

**Closed by PiotrMachowski** 2021-04-29 15:57 UTC
