### ISSUE TITLE
Support for Mi Robot Vacuum-Mop 2 Pro (ijai.vacuum.v3)

### ISSUE THREAD

**Issue by SomtaawKith** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#494] opened 2023-11-23 09:37 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v3

### What is its name?

Mi Robot Vacuum-Mop 2 Pro

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment] 2023-11-23 11:01
Duplicate of #200

**Closed by PiotrMachowski** 2023-11-23 11:01 UTC
Labels: enhancement, new platform
