### ISSUE TITLE
Xiaomi Cloud Map Extractor error

### ISSUE THREAD

**Issue by rotrials** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#203] opened 2021-12-16 22:09 UTC
The problem
Xiaomi Cloud Map Extractor reported some errors in the log.

What version of Home Assistant Core has the issue?
core-2021.12.2

What was the last working version of Home Assistant Core?
don't remember, I haven't check the log in a while...

What type of installation are you running?
Home Assistant Container

Integration causing the issue
Xiaomi Cloud Map Extractor

Example YAML snippet
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret ip_address
    token: !secret Robot_vacuum_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    store_map_raw: true
    draw: ['all']
    attributes:
      - calibration_points

Anything in the logs that might be useful for us?
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:502
Integration: Camera (documentation, issues)
First occurred: 12:03:52 AM (1 occurrences)
Last logged: 12:03:52 AM

The camera entity camera.xiaomi_cloud_map_extractor does not support requesting width and height, please open an issue with the integration author
Additional information

**Comment by rotrials** [comment] 2021-12-16 22:10
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:718
Integration: Camera (documentation, issues)
First occurred: December 16, 2021, 11:57:32 PM (2 occurrences)
Last logged: 12:01:07 AM

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05


I have tried to change update interval with no success...

**Comment by PiotrMachowski** [comment] 2021-12-17 01:25
Duplicate of #168

**Closed by PiotrMachowski** 2021-12-17 01:25 UTC
