### ISSUE TITLE
Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by nilsoo** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#526] opened 2024-04-09 05:48 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera' is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>
see:
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roborock

### What version of Home Assistant do you use?

Core-2024.4.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
-
```

### Errors shown in the HA logs (if applicable)

```shell
Yes
```

**Comment by PiotrMachowski** [comment] 2024-04-09 09:24
Duplicate of #505

**Closed by PiotrMachowski** 2024-04-09 09:24 UTC
Labels: bug
