### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by daggr8** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#32] opened 2020-10-25 13:19 UTC
Hi,

I get this in the log when i added more than the "basic" config. 
Running HA in docker. Any tips?

```
`2020-10-25 14:12:22 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.s5max fails

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update await self.hass.async_add_executor_job(self.update) # type: ignore
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 187, in update map_data = self._connector.get_map(map_name, self._colors, self._drawables, self._texts, self._sizes,
File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 105, in get_map map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 81, in parse ImageHandler.draw_texts(map_data.image, texts)
File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 189, in draw_texts ImageHandler.__draw_text__(image, text_config[CONF_TEXT], x, y, text_config[CONF_COLOR],
File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 235, in __draw_text__ ImageHandler.__draw_on_new_layer__(image, draw_func)
File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 249, in __draw_on_new_layer__ draw_function(draw)
File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 231, in draw_func font = ImageFont.truetype(font_file, font_size)
File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype return freetype(font)
File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype return FreeTypeFont(font, size, index, encoding, layout_engine)
File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 169, in __init__ if core.HAVE_RAQM:
File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 43, in __getattr_ _raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed`
```

**Comment by PiotrMachowski** [comment] 2020-10-25 13:49
Just remove `font:` from `texts` section.

Duplicate of #20

**Closed by PiotrMachowski** 2020-10-25 13:49 UTC
