### ISSUE TITLE
Four different maps?

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#266] opened 2022-03-26 00:01 UTC
Hi,

I have two issues.

Can I get 4 maps saved in the same vacuum?
Can I set one of them as default map?

**Comment by PiotrMachowski** [comment] 2022-03-26 00:20
Duplicate of #67

**Comment by PiotrMachowski** [comment] 2022-03-26 00:21
Right now it's not possible. Only current map is retrieved

**Closed by PiotrMachowski** 2022-03-26 00:20 UTC
