### ISSUE TITLE
xiaomi 2s mop

### ISSUE THREAD

**Issue by mattiabrunello5** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#443] opened 2023-06-17 14:49 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v19

### What is its name?

xiaomi 2s mop

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py:18 
Integration: xiaomi_cloud_map_extractor (documentation, issues) 
First occurred: 16:11:52 (341 occurrences) 
Last logged: 16:40:16

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Other info

I don't find any file related to the vacuum in config/tmp/ folder can you help me to retrive the map

**Comment by mattiabrunello5** [comment] 2023-06-17 18:20
Now the camera view show fail to login

**Comment by PiotrMachowski** [comment] 2023-06-17 22:42
Duplicate of #200

**Closed by PiotrMachowski** 2023-06-17 22:42 UTC
Labels: enhancement, new platform
