### ISSUE TITLE
Mija 3c

### ISSUE THREAD

**Issue by abdala666** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#542] opened 2024-07-17 19:11 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [X] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v18

### What is its name?

Xiaomi Vacuum Mop 3C

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
map dosent appers
```

**Comment by PiotrMachowski** [comment] 2024-07-17 19:14
Duplicate of #200

**Closed by PiotrMachowski** 2024-07-17 19:14 UTC
Labels: enhancement, new platform
