### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by dm82m** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#207] opened 2021-12-21 08:34 UTC
2021-12-21 09:15:12 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by PiotrMachowski** [comment] 2021-12-21 09:10
Duplicate of #196

**Closed by PiotrMachowski** 2021-12-21 09:10 UTC
