### ISSUE TITLE
dreame.vacuum.p2041o is not supported ?

### ISSUE THREAD

**Issue by siminkuv** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#208] opened 2021-12-26 10:38 UTC
I tried to integrate Xiaomi xiaomi vacuum mop 2 pro + Unfortunately HomeAssistant shows me an error message "dreame.vacuum.p2041o is not supported"

![image](https://user-images.githubusercontent.com/81320257/147405621-d9e42b51-63e4-44b9-85e9-a74226d51367.png)

**Comment by PiotrMachowski** [comment] 2021-12-26 12:13
Duplicate of #126

**Closed by PiotrMachowski** 2021-12-26 12:13 UTC
