### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bazookastas** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#492] opened 2023-11-18 00:06 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v18

### What is its name?

Xiaomi Mi Mijia Robot Vacuum Mop 3C

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment] 2023-11-18 00:08
Duplicate of #200

**Closed by PiotrMachowski** 2023-11-18 00:08 UTC
Labels: enhancement, new platform
