### ISSUE TITLE
Cannot create map

### ISSUE THREAD

**Issue by BokovDenis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#169] opened 2021-09-07 07:08 UTC
Hi there, I'm trying to integrate my vacuum into it, but getting errors.
Maybe I'm missing something?
Error I'm getting:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 257, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 314, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 15, in decode_map
    return MapDataParserViomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 157, in parse
    MapDataParserViomi.parse_section(buf, 'unknown2', map_id)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 313, in parse_section
    raise ValueError(
ValueError: error parsing section unknown2 at offset 0x9c6fa: magic check failed 0x900c00fe
```

Camera configuration:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.2.10
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "ru"
    name: "Map Vacuum Cleaner"
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment] 2021-09-07 07:51
Duplicate of #153

**Closed by PiotrMachowski** 2021-09-07 07:51 UTC
