### ISSUE TITLE
Support for XIAOMI Mi Robot Vacuum-Mop 2 Pro  Model: ijai.vacuum.v3

### ISSUE THREAD

**Issue by sigmastk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#551] opened 2024-08-20 21:34 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v3

### What is its name?

Mi Robot Vacuum-Mop 2 Pro

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Other info

I do not know if the difference from 2 pro to 2 pro+ is substantial. It seems to me that it is a completely different manufacturer.

I know this "request" is a long shot, but I really like your integration and would like it to support my vacuum cleaner.

If you require anything from my side, please do not hesitate to contact me.

**Comment by PiotrMachowski** [comment] 2024-08-21 02:19
Duplicate of #200

**Comment by Jataganich** [comment] 2024-10-04 05:12
+ 1 для ijai.vacuum.v3

**Closed** 2024-10-04 09:38 UTC
Labels: enhancement, new platform
