### ISSUE TITLE
Update for camera.xiaomi_cloud_map_extractor fails

### ISSUE THREAD

**Issue by galamarco** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#402] opened 2023-02-07 14:33 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello,
I have a lot of error in log and I can't see the map.
Here the error:

```
Questo errore ha avuto origine da un'integrazione personalizzata.
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py:18
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 15:13:01 (34 occurrences)
Last logged: 15:15:45
Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable

```

### What version of an integration has described problem?

last version

### What was the last working version of an integration?

last version

### What vacuum model do you have problems with?

Xiaomi Robot Vacuum-Mop 2S

### What version of Home Assistant do you use?

2023.2.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    host: 192.168.6.63
    token: '514175344c62475151395a5667646a35'
    username: '+393440480329'
    password: 'Sviluppo.1864!'
    force_api: dreame
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment] 2023-02-07 16:01
Duplicate of #200

**Closed by PiotrMachowski** 2023-02-07 16:01 UTC
Labels: bug
