### ISSUE TITLE
No map from Xiaomi Robot Vacuum-Mop 2S

### ISSUE THREAD

**Issue by galamarco** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#324] opened 2022-08-06 00:31 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello, I bought a Xiaomi Robot Vacuum-Mop 2S an I would like to manage it in the home assistant.
I setting a lot but this is the result.
![image](https://www.webg.it/images/articoli/2022-08/Screenshot_1.png)

I have a lot of errror:

```
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:778
Integration: Telecamera (documentation, issues)
First occurred: 02:23:10 (4 occurrences)
Last logged: 02:23:41

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10
```

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 02:20:22 (11 occurrences)
Last logged: 02:23:34

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:514
First occurred: 02:23:10 (1 occurrences)
Last logged: 02:23:10

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
```

### What version of am integration has described problem?

 v2.2.0

### What vacuum model do you have problems with?

Xiaomi Robot Vacuum-Mop 2S

### What version of Home Assistant do you use?

2022.8.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    host: 192.168.6.63
    token: 'XXX'
    username: XXX
    password: XXX
    force_api: xiaomi
    scan_interval: 10
    draw: ['all']
    attributes: 
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

I have a lot of errror:

```shell
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:778
Integration: Telecamera (documentation, issues)
First occurred: 02:23:10 (4 occurrences)
Last logged: 02:23:41

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10
```

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 02:20:22 (11 occurrences)
Last logged: 02:23:34

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:514
First occurred: 02:23:10 (1 occurrences)
Last logged: 02:23:10

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
```

**Comment by Caliban2017** [comment] 2022-08-24 21:06
Can confirm it, have the same Vacuum Cleaner Model and get the exact same Error Codes in the Log when trying to receive the Map. Anything new here?

**Comment by PiotrMachowski** [comment] 2022-08-25 08:00
@galamarco @Caliban2017 what is model code of this vacuum?

**Comment by Caliban2017** [comment] 2022-08-25 11:31
@PiotrMachowski 

I hope that Infos will help:

`Model
ijai.vacuum.v19
Lan IP
192.168.XXX.XXX
MAC address
04:39:26:XX:XX:XX
Entity class
MiotVacuumEntity
Exclude miot services
order
Exclude miot properties
zone_points, restrict_points, target_point
Miot type
urn:miot-spec-v2:device:vacuum:0000A006:ijai-v19:1
Vacuum.status
4
Vacuum.fault
2.103
Vacuum.mode
1
Vacuum.sweep type
0
Vacuum.on
[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1]
Disturb.dnd enable
1
Disturb.dnd start hour
23
Disturb.dnd start minute
0
Disturb.dnd end hour
9
Disturb.dnd end minute
0
Disturb.multi prop dnd
[1,23,0,9,0]
Map.remember state
1
Map.cur map ID
1.661.371.267
Map.map num
1
Map.cur cleaning path
—
Map.build map
0
Map.has new map
0
Sweep.repeat state
0
Sweep.door state
3
Sweep.cloth state
0
Sweep.suction state
2
Sweep.water state
2
Sweep.mop route
0
Sweep.side brush life
100
Sweep.side brush hours
180
Sweep.main brush life
100
Sweep.main brush hours
360
Sweep.hypa life
100
Sweep.hypa hours
180
Sweep.mop life
100
Sweep.mop hours
180
Sweep.direction.error
-4001 Property is not readable
Sweep.time zone
-7.200
Sweep.cur lang
de_DE
Sweep.cleaning time
12
Sweep.cleaning area
12
Sweep.dirt recognize
0
Sweep.pet recognize
0
Sweep.ai recognize
0
Sweep.carpet booster
0
Sweep.multi prop vacuum
[0,3,0,2,2,0,-7200,12,12.3,0,"de_DE","378432SD2202A02500","en_US",3,-1,0,0,1,2,1]
Sweep.carpet avoid.error
-4001 Property is not readable
Sweep.tank shake
1
Sweep.shake shift
2
Sweep.map encrypt
1
Alarm
false
Alarm.volume
10
State updater
lan
Vacuum.status desc
Charging
Sub entities
vacuum-2.status-1, battery-3.battery_level-1`

**Comment by PiotrMachowski** [comment] 2022-08-25 16:36
Ok, it is `ijai.vacuum.v19`, so it is not supported right now.

duplicate of #200

**Closed by PiotrMachowski** 2022-08-25 16:36 UTC
Labels: bug

**Comment by Georgi317** [comment] 2024-10-30 13:22
> Ок, она есть `ijai.vacuum.v19`, поэтому прямо сейчас она не поддерживается.

Добрый день. А когда будет произведена поддержка данного пылесоса?
