### ISSUE TITLE
Error: Failed to retreive map from vacuum. Was working flawlesly, stopped working without any updates

### ISSUE THREAD

**Issue by vajnorcan** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#516] opened 2024-03-06 07:45 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I've set it up this morning, was working all day, happy, sent the paypal as a token of appreciation. However, it's unable to retreive the map few hours later without doing any updates on the system. I've double checked the IP (which is static) of the vacuum, token, and passwords, however I'm unable to get the map rendered. It doesn't even show up when the vacuum is running (other controls are working fine)

**Update**
Well, it seems like I'm unable to see the map in the mi home app neither, this never happened. I wonder if this integration could've deleted it / corrupted it?

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

v2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2024.2.5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.....46
    token: 6----6
    username: m----@gmail.com
    password: V----3
    country: sg
    draw: ["all"]
    attributes:
      - calibration_points
      - vacuum_position
```

### Errors shown in the HA logs (if applicable)

```shell
-- I don't think this is related as it's just a warning. not sure if there are any other log entries elsewhere

2024-03-06 17:44:03.786 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by vajnorcan** [comment] 2024-03-06 07:56
Well, as per update, it seem like I'm unable to see the map in the mi home app, though this was never a problem before. I guess I will have to re-learn it again?!

**Comment by cathelest** [comment] 2024-03-06 09:20
Not sure about mi app

But hoping it may be similar to others

Is there a option to manage maps, it may have somehow created a second blank one, the old one should still be there and allow u to restore possibly,

I have had this happen a few times with my roborock and xiaomi app

**Comment by vajnorcan** [comment] 2024-03-06 09:21
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/422

Exhibiting the same behavior as there. Closing this thread as we can keep going in there.

**Comment by vajnorcan** [comment] 2024-03-06 09:22
> Not sure about mi app
> 
> But hoping it may be similar to others
> 
> Is there a option to manage maps, it may have somehow created a second blank one, the old one should still be there and allow u to restore possibly,
> 
> I have had this happen a few times with my roborock and xiaomi app

Well, it not sure how would I do it. Seems like for some people restarting the roborock worked, however it's not working for me. Let's keep the discussion going in the thread I've posted above

**Comment by PiotrMachowski** [comment] 2024-03-06 13:50
Duplicate of #422

**Closed by PiotrMachowski** 2024-03-06 13:50 UTC
Labels: bug

**Comment by tovy14** [comment] 2024-03-28 12:32
Sorry for piggy backing on this issue, but to be clear about this, both the blueprints should be used: disable and update? Or only update, with long update time?
