### ISSUE TITLE
The possibility to overlay a SVG/PNG to the map.

### ISSUE THREAD

**Issue by maxi1134** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#436] opened 2023-05-19 05:03 UTC
### Description

A lot of us are into generating house plans. 
I thought about this, and It would be great if we could overlay a png/svg map to the current robovat position map.

It would make selecting zones for messes easier.

### Solution

A parameters that inputs an image and a scale/positions.

### Alternatives

I thought about trying to stick a picture element over this card. But that seems too hacky.

**Comment by PiotrMachowski** [comment] 2023-05-19 09:42
Duplicate of #39

**Closed by PiotrMachowski** 2023-05-19 09:42 UTC
Labels: enhancement
