### ISSUE TITLE
Error displaying the map on HA

### ISSUE THREAD

**Issue by salvatore-disavio** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#546] opened 2024-07-24 00:50 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The map doesn't appear, only the message "Invalid calibration, please check your configuration".

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

Xiaomi Robot Vacuum-Mop 2S

### What version of Home Assistant do you use?

2024.7.3

### What type of installation are you running?

Home Assistant Core

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: X
    token: X
    username: X
    password: X
    draw: ['all']
    attributes:
      - calibration_points
    scan_interval:
        seconds: 10
    auto_update: true
```

**Comment by PiotrMachowski** [comment] 2024-07-24 02:22
please provide vacuum model identifier (in format manufacturer.vacuum.model)

**Comment by salvatore-disavio** [comment] 2024-07-24 08:41
ijai.vacuum.v19

Il Mer 24 Lug 2024, 04:22 Piotr Machowski ***@***.***> ha
scritto:

**Comment by PiotrMachowski** [comment] 2024-07-25 09:01
> ijai.vacuum.v19

Duplicate of #200

**Closed by PiotrMachowski** 2024-07-25 09:01 UTC
Labels: bug
