### ISSUE TITLE
Add support for vacuum.ijai_v10

### ISSUE THREAD

**Issue by paulakfleck** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#369] opened 2022-11-19 04:08 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [X] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

vacuum.ijai_v10

### What is its name?

Mi Robot Vacuum-Mop 2 Lite

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment] 2022-11-19 10:33
Duplicate of #200

**Closed by PiotrMachowski** 2022-11-19 10:33 UTC
Labels: enhancement, new platform
