### ISSUE TITLE
integrate xiaomi vacum mop 2s

### ISSUE THREAD

**Issue by mattiabrunello5** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#372] opened 2022-12-01 13:09 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v19

### What is its name?

xiaomi vacum mop 2s

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
2022-12-01 11:13:10.844 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2022-12-01 11:13:11.885 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

### Other info

in camera view its shows " failed  to retrieve map from vacuum"

**Comment by PiotrMachowski** [comment] 2022-12-01 15:17
duplicate of #200

**Closed by PiotrMachowski** 2022-12-01 15:17 UTC
Labels: enhancement, new platform
