### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by adonixis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#513] opened 2024-02-22 13:34 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/1766863/0bd9a8e7-2c93-4485-83cd-a3a4148413e3)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/1766863/ce2c6b35-56b6-4b75-b8d6-50cf348bc4fc)
I'm getting this error with my vacuum cleaner Xiaomi Robot Vacuum S10 https://home.miot-spec.com/s/ijai.vacuum.v17

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

ijai.vacuum.v17

### What version of Home Assistant do you use?

Core 2024.2.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    store_map_raw: true
    store_map_image: true
    store_map_path: "/tmp"
```

### Errors shown in the HA logs (if applicable)

```shell
Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
Got error when receiving: timed out
```

**Comment by PiotrMachowski** [comment] 2024-02-22 14:06
Duplicate of #200

**Closed by PiotrMachowski** 2024-02-22 14:06 UTC
Labels: bug

**Comment by adonixis** [comment] 2024-02-22 14:09
> Duplicate of #200

Ok, thanks! Is there any way I can help with adding support for the ijai.vacuum.v17 model?

**Comment by adonixis** [comment] 2024-02-22 14:24
> All info is in #200 :) you can if you can decode ijai map protocol

Can you send me any raw ijia map please? Because I can't get it from my vacuum cleaner.

**Comment by PiotrMachowski** [comment] 2024-02-22 17:08
I can't send it to you without permission of the creator. I see that you have asked this question in the original issue, somebody should be able to send it to you.

**Comment by adonixis** [comment] 2024-02-22 17:14
No problem, I understand
