### ISSUE TITLE
Xiaomi Robot Vacuum Mop 2S - Can't get map to show...

### ISSUE THREAD

**Issue by rucanunes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#375] opened 2022-12-18 13:25 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I've tried everything in the book but I can't get my map to show.
![Screenshot 2022-12-18 at 13-22-22 Cozinha – Home Assistant](https://user-images.githubusercontent.com/44728693/208300850-81895244-f0cc-4bd4-9e4c-5cb6ea2949fc.png)

### What version of an integration has described problem?

2.2.0

### What was the last working version of an integration?

First Time Trying

### What vacuum model do you have problems with?

Xiaomi Robot Vacuum Mop 2S

### What version of Home Assistant do you use?

2022.12.7

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
I have camera: !include camera.yaml

  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_url
    token: !secret xiaomi_token
    username: !secret xiaomi_user
    password: !secret xiaomi_pass
    force_api: roidmi
    store_map_raw: true
    store_map_path: "/config/tmp"
    auto_update: true
    scan_interval:
      seconds: 300 #10minutes
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
2022-12-18 12:58:06.545 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
self._handle_map_data(map_name)
File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
response = self.get_raw_map_data(map_name)
File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
map_url = self.get_map_url(map_name)
File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable
```

### Additional information

This is my first time trying the map addon....
Could someone please tell me what I'm doing wrong?

Tks!

![Screenshot 2022-12-18 at 13-22-11 Cozinha – Home Assistant](https://user-images.githubusercontent.com/44728693/208300860-639bb986-e777-4232-823e-c8ce04adbf2c.png)

**Comment by PiotrMachowski** [comment] 2022-12-18 13:32
Duplicate of #200

**Closed by PiotrMachowski** 2022-12-18 13:32 UTC
Labels: bug

**Comment by rucanunes** [comment] 2022-12-18 15:45
I'm sorry I didn't saw that post. I did searched however.
Thank you!!

**Comment by PiotrMachowski** [comment] 2022-12-18 16:54
No problem, it's not obvious of you don't know your model code
