### ISSUE TITLE
SUPPORT_ON_OFF will be deprecated  in HA 2025.1

### ISSUE THREAD

**Issue by geeForceOne** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#557] opened 2024-10-05 06:46 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration

### What version of an integration has described problem?

v2.2.4

### What vacuum model do you have problems with?

irrelevant

### What version of Home Assistant do you use?

2024.10.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
not relevant
```

**Comment by PiotrMachowski** [comment] 2024-10-07 11:18
Duplicate of #505

**Closed by PiotrMachowski** 2024-10-07 11:18 UTC
Labels: bug
