### ISSUE TITLE
custom_components.xiaomi_cloud_map_extractor.camera Source: custom_components/xiaomi_cloud_map_extractor/camera.py:356 intégration: Xiaomi Cloud Map Extractor

### ISSUE THREAD

**Issue by Helloamiral** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#554] opened 2024-09-17 15:51 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Found an unsupported model 'roborock.vacuum.a75' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

### What version of an integration has described problem?

V2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.a75

### What version of Home Assistant do you use?

2024.9.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_qrevo
vacuum_platform: humbertogontijo/homeassistant-roborock
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```

**Comment by Quentame** [comment] 2024-10-13 08:41
Thanks to read the log, you created the issue in the wrong repository.
----
Merci de lire la log, vous avez créé l'anomalie dans le mauvais répertoire

**Comment by Quentame** [comment] 2024-10-13 08:42
Duplicate of #552

**Closed** 2024-10-13 16:08 UTC
Labels: bug
