### ISSUE TITLE
Support for dreame.vacuum.p2041o

### ISSUE THREAD

**Issue by Jezze83** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#221] opened 2022-01-15 11:52 UTC
![vacuum](https://user-images.githubusercontent.com/10639795/149620804-e9d71b3d-8078-48e8-ac28-d48663f23080.JPG)

So this model not supported? Is it possible get it working?

**Comment by PiotrMachowski** [comment] 2022-01-15 12:03
Duplicate of #126

**Closed by PiotrMachowski** 2022-01-15 12:03 UTC
