### ISSUE TITLE
Add support for Xiaomi Vacuum Robot S10 (ijai.vacuum.v17)

### ISSUE THREAD

**Issue by swiderrr** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#475] opened 2023-10-10 21:43 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

ijai.vacuum.v17

### What is its name?

Xiaomi Vacuum Robot S10

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
2023-10-10 23:39:37.726 WARNING (SyncWorker_1) [miio.device] Found an unsupported model 'ijai.vacuum.v17' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2023-10-10 23:39:38.913 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HP LaserJet M110w (42A273)' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-10-10 23:39:46.638 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2023-10-10 23:39:54.801 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-10-10 23:39:54.804 WARNING (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to recover failed command
2023-10-10 23:40:11.825 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

**Comment by PiotrMachowski** [comment] 2023-10-10 22:13
Duplicate of #200

**Closed by PiotrMachowski** 2023-10-10 22:13 UTC
Labels: enhancement, new platform
