### ISSUE TITLE
Problems with discovery of ijai.vacuum.v19

### ISSUE THREAD

**Issue by CommanderRedYT** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#568] opened 2024-12-04 08:24 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When configuring the vacuum, the errors below (see attached logs) show up. I found some people who also have the ijai.vacuum.v19, but nothing they described helped in my case.

I also do not have the different-subnet problem, as it is a single IP range.

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

None

### What vacuum model do you have problems with?

ijai.vacuum.v19

### What version of Home Assistant do you use?

2024.11.3

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ['all']
    attributes:
      - calibration_points
    force_api: 'xiaomi'
```

### Errors shown in the HA logs (if applicable)

```shell
2024-12-04 09:13:05.465 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 09:13:06.901 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-12-04 09:13:06.902 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-12-04 09:13:06.911 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-04 09:13:12.776 WARNING (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to discover the device 192.168.0.161
2024-12-04 09:13:16.912 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
```

**Comment by PiotrMachowski** [comment] 2024-12-04 13:00
Duplicate of #200

**Closed by PiotrMachowski** 2024-12-04 13:00 UTC
Labels: bug
