### ISSUE TITLE
roborock.vacuum.a65

### ISSUE THREAD

**Issue by pedro639** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#543] opened 2024-07-19 03:14 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roborock.vacuum.a65

### What is its name?

Roborock S7 max ultra

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

`Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

`SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration`

**Comment by PiotrMachowski** [comment] 2024-07-20 02:27
Does the camera entity work?

**Comment by pedro639** [comment] 2024-07-20 02:33
It does yes, I have the map completely here, I'm not sure if it is updating correctly tho. But after I configured it the camera entity got the map straight away.

________________________________

**Comment by pedro639** [comment] 2024-07-20 02:33
Clesed by accident

**Comment by PiotrMachowski** [comment] 2024-07-20 02:44
Duplicate of #505

**Closed by PiotrMachowski** 2024-07-20 02:44 UTC
Labels: enhancement, new platform
