### ISSUE TITLE
Error map with mi robot vacuum mop 2 pro

### ISSUE THREAD

**Issue by Altar82** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#362] opened 2022-11-07 20:37 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

hi,i'm tryng to integrate map of mi robot vacuum mop 2 pro,but i got this error:

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py:23
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 21:18:04 (13 occurrences)
Last logged: 21:19:01

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 23, in decode_map
    raw_map_string = raw_map.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 21:15:28 (10 occurrences)
Last logged: 21:18:01

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

i'm trying too with force_api: viomi in config,like this:

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.188.66
    token: ******************
    username: ***********
    password: **************
    force_api: viomi

and i get this error type:

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py:97
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 20:18:23 (768 occurrences)
Last logged: 21:30:40

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 23, in decode_map
    return MapDataParserViomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 97, in parse
    if not map_data.image.is_empty:
AttributeError: 'NoneType' object has no attribute 'is_empty'

### What version of an integration has described problem?

v 2.2.0

### What vacuum model do you have problems with?

ijai.vacuum.v3

### What version of Home Assistant do you use?

Home Assistant 2022.11.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.188.66
    token: *************
    username: ***********
    password: ***********
    force_api: viomi
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py:23
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 21:18:04 (13 occurrences)
Last logged: 21:19:01

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 23, in decode_map
    raw_map_string = raw_map.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 21:15:28 (10 occurrences)
Last logged: 21:18:01

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

**Comment by PiotrMachowski** [comment] 2022-11-07 20:52
Duplicate of #200

**Closed by PiotrMachowski** 2022-11-07 20:52 UTC
Labels: bug
