### ISSUE TITLE
Failed to retrieve model 

### ISSUE THREAD

**Issue by bussio** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#211] opened 2021-12-31 17:45 UTC
Since a few days I have the following error with the custom component:

"This error was caused by a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288 
Integration: xiaomi_cloud_map_extractor (documentation, issues) 
First occurred: 18:37:33 (3 occurrences) 
Last logged: 18:37:45

Failed to retrieve model"

I use the Xiaomi Roborock S6 ....

This is my entry in the configuration.yaml:
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    name: "Xiaomi Roborock S6 Karte"
    colors:
      color_map_inside: [252, 250, 250]
      color_map_outside: [252, 250, 250]                                        # weiß
      color_map_wall: [225, 225, 225]
      color_map_wall_v2: [110, 110, 110]
      color_grey_wall: [252, 250, 250]
      color_path: [255, 255, 255]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [1, 195, 120]
      color_robo: [236, 236, 236]
      color_unknown: [225, 225, 225]
      color_scan: [225, 225, 225]
    room_colors:
      1: [113, 203, 222]
      2: [253, 211, 82]
      3: [145, 200, 255]
      4: [245, 142, 110]
      5: [113, 203, 222]
      6: [253, 211, 82]
      7: [145, 200, 255]
      8: [245, 142, 110]
      9: [113, 203, 222]
      10: [253, 211, 82]
      11: [145, 200, 255]
      12: [245, 142, 110]
      13: [113, 203, 222]
      14: [253, 211, 82]
      15: [145, 200, 255]
      16: [245, 142, 110]
      17: [113, 203, 222]
      18: [253, 211, 82]
      19: [145, 200, 255]
      20: [245, 142, 110]
    draw: ["all"]
    texts:
      - text: "WZ außen"
        x: 25
        y: 45
        font_size: 100
      - text: "WZ innen"
        x: 45
        y: 45
        font_size: 100
    map_transformation:
      scale: 5 
      rotate: 0
      trim:
        top: 15
        bottom: 15
        left: 15
        right: 15
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - walls
      - zones
    scan_interval:
      seconds: 5
    auto_update: true

**Comment by PiotrMachowski** [comment] 2021-12-31 19:14
Duplicate of #192

**Closed by PiotrMachowski** 2021-12-31 19:14 UTC
