### ISSUE TITLE
Error on request - invalid config for fds

### ISSUE THREAD

**Issue by ruvasik** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#496] opened 2023-11-30 13:51 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I got errors on try get map

(i putted log debug in vacuum_v2.py)

```
2023-11-30 16:44:10.015 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Logged in
2023-11-30 16:44:10.015 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving device info, country: None
2023-11-30 16:44:13.806 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieved device model: ijai.vacuum.v17
2023-11-30 16:44:13.806 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Created device, used api: None

2023-11-30 16:44:25.947 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2023-11-30 16:44:25.948 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.common.vacuum_v2] get_map_url1: 4176214583, 1059631891, 0
2023-11-30 16:44:25.948 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.common.vacuum_v2] get_map_url2: https://ru.api.io.mi.com/app/v2/home/get_interim_file_url, {'data': '{"obj_name":"417621xxxx/105963xxxx/0"}'}
2023-11-30 16:44:26.385 DEBUG (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.common.vacuum_v2] get_map_url3: {'code': -6, 'message': 'invalid config for fds', 'result': None}
```

### What version of an integration has described problem?

v.2.2.1

### What vacuum model do you have problems with?

ijai.vacuum.v17

### What version of Home Assistant do you use?

2023.11.3

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    # force_api: xiaomi
    # country: cn
    store_map_raw: true
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment] 2023-11-30 14:10
This model is not currently supported.

Duplicate of #200

**Closed as not planned by PiotrMachowski** 2023-11-30 14:10 UTC
Labels: bug
