### ISSUE TITLE
HA 2021.12.3 Warning

### ISSUE THREAD

**Issue by va77** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#206] opened 2021-12-18 17:01 UTC
Hi

2021-12-18 18:29:27 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by PiotrMachowski** [comment] 2021-12-18 23:24
Duplicate of #196

**Closed by PiotrMachowski** 2021-12-18 23:24 UTC
