### ISSUE TITLE
Error: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by TorAllex** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#478] opened 2023-10-17 16:34 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi! Can't get map, only errors in log :)
I've try [solution](https://community.home-assistant.io/t/roborock-map-camera-is-not-shown-every-24h/573404/9), but nothing...

### What version of an integration has described problem?

2.2.1

### What vacuum model do you have problems with?

Xiaomi Mi Mijia Robot Vacuum Mop 3C (B106CN)

### What version of Home Assistant do you use?

Supervisor 2023.10.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    scan_interval: 14400
    country: cn
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:732
First occurred: 18:49:59 (417 occurrences)
Last logged: 19:23:56
Update for camera.xiaomi_cloud_map_extractor fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by PiotrMachowski** [comment] 2023-10-17 16:45
Your vacuum model is `ijai.vacuum.v18`, it is not supported at this moment. 

Duplicate of #200

**Closed by PiotrMachowski** 2023-10-17 16:45 UTC
Labels: bug
