### ISSUE TITLE
Support for multiple vacuum?

### ISSUE THREAD

**Issue by noiseboy303** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#134] opened 2021-06-15 18:46 UTC
Hello,

  I was wondering if it supports multiple vacuums, we have 2 and I can only see one map!

Thanks for the great work!

**Comment by PiotrMachowski** [comment] 2021-06-15 18:49
Yes, you have to define 2 cameras with different `name` provided.

Duplicate of #119

**Closed** 2021-06-15 18:49 UTC

**Comment by noiseboy303** [comment] 2021-06-15 18:51
Oh Geez, Sorry, I did not see the post 119!

Thanks for the quick answer!


Martin Pare
***@***.***
