### ISSUE TITLE
New Xiaomi Mini Vacuum 3C (join.vacuum.v18) 

### ISSUE THREAD

**Issue by Keks1975** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#415] opened 2023-03-17 08:18 UTC
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

join.vacuum.v18

### What is its name?

Xiaomi Mini Vacuum 3C

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
#
Log Details (ERROR)
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:272
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 11:11:50 AM (1 occurrences)
Last logged: 11:11:50 AM

Failed to retrieve model


#
Log Details (WARNING)
This error originated from a custom integration.

Logger: miio.device
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 11:11:50 AM (1 occurrences)
Last logged: 11:11:50 AM

Found an unsupported model 'ijai.vacuum.v18' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

#
Log Details (WARNING)
This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:273
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 11:12:07 AM (1 occurrences)
Last logged: 11:12:07 AM

Got exception while fetching the state: Unable to recover failed command

#
Log Details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:541
First occurred: 11:11:49 AM (2 occurrences)
Last logged: 11:12:21 AM

Update of camera.dzhordzh_map is taking over 10 seconds
Update of vacuum.ijai_v18_d22c_robot_cleaner is taking over 10 seconds

#
Log Details (ERROR)
This error originated from a custom integration.

Logger: miio.miioprotocol
Source: custom_components/xiaomi_miot/__init__.py:655
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:12:27 AM (1 occurrences)
Last logged: 11:12:27 AM

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

#
Log Details (ERROR)
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1384
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:12:27 AM (1 occurrences)
Last logged: 11:12:27 AM

ДжоРдж(ijai.vacuum.v18): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 9}, 'disturb.dnd_enable': {'siid': 12, 'piid': 1}, 'disturb.dnd_start_hour': {'siid': 12, 'piid': 2}, 'disturb.dnd_start_minute': {'siid': 12, 'piid': 3}, 'disturb.dnd_end_hour': {'siid': 12, 'piid': 4}, 'disturb.dnd_end_minute': {'siid': 12, 'piid': 5}, 'disturb.multi_prop_dnd': {'siid': 12, 'piid': 7}, 'map.remember_state': {'siid': 10, 'piid': 1}, 'map.cur_map_id': {'siid': 10, 'piid': 2}, 'map.map_num': {'siid': 10, 'piid': 3}, 'map.cur_cleaning_path': {'siid': 10, 'piid': 5}, 'map.build_map': {'siid': 10, 'piid': 14}, 'map.has_new_map': {'siid': 10, 'piid': 19}, 'sweep.repeat_state': {'siid': 7, 'piid': 1}, 'sweep.door_state': {'siid': 7, 'piid': 3}, 'sweep.cloth_state': {'siid': 7, 'piid': 4}, 'sweep.suction_state': {'siid': 7, 'piid': 5}, 'sweep.water_state': {'siid': 7, 'piid': 6}, 'sweep.mop_route': {'siid': 7, 'piid': 7}, 'sweep.side_brush_life': {'siid': 7, 'piid': 8}, 'sweep.side_brush_hours': {'siid': 7, 'piid': 9}, 'sweep.main_brush_life': {'siid': 7, 'piid': 10}, 'sweep.main_brush_hours': {'siid': 7, 'piid': 11}, 'sweep.hypa_life': {'siid': 7, 'piid': 12}, 'sweep.hypa_hours': {'siid': 7, 'piid': 13}, 'sweep.mop_life': {'siid': 7, 'piid': 14}, 'sweep.mop_hours': {'siid': 7, 'piid': 15}, 'sweep.time_zone': {'siid': 7, 'piid': 20}, 'sweep.cur_lang': {'siid': 7, 'piid': 21}, 'sweep.cleaning_time': {'siid': 7, 'piid': 22}, 'sweep.cleaning_area': {'siid': 7, 'piid': 23}, 'sweep.dirt_recognize': {'siid': 7, 'piid': 35}, 'sweep.pet_recognize': {'siid': 7, 'piid': 36}, 'sweep.ai_recognize': {'siid': 7, 'piid': 42}, 'sweep.carpet_booster': {'siid': 7, 'piid': 44}, 'sweep.multi_prop_vacuum': {'siid': 7, 'piid': 45}, 'sweep.tank_shake': {'siid': 7, 'piid': 48}, 'sweep.shake_shift': {'siid': 7, 'piid': 50}, 'sweep.map_encrypt': {'siid': 7, 'piid': 55}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}}, max_properties: 10/46


#
Log Details (ERROR)
This error originated from a custom integration.

Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 11:12:07 AM (3 occurrences)
Last logged: 11:12:40 AM

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
```

### Other info

Good afternoon! great idea Xiaomi Cloud Map Extractor. I have Xiaomi Mini Vacuum 3C firmware (join.vacuum.v18) (4.3.3_0027). Home assistant 2023.3.4,
vacuum cleaner parameters https://home.miot-spec.com/spec/ijey .vacuum.v18
There is a desire to support this model in Xiaomi Cloud Map Extractor Thank you.

Available APIs Available APIs suspect "ijai"

**Comment by PiotrMachowski** [comment] 2023-03-17 09:50
It is `ijai.vacuum.v18`, not `join.vacuum.v18`, so this issue is a duplicate of #200

**Closed by PiotrMachowski** 2023-03-17 09:50 UTC
Labels: enhancement, new platform
